### ISSUE TITLE
Is it possible to use this in node.js?

### ISSUE THREAD

**Issue by enthusapp** [johntalton/mcp2221#326]
Hi,
Is it possible to use this in node.js?
If possible, it could be very helpful. 
Because node.js is easy to handle for me.

If not possible now, do you guide or suggest any tip to upgrade this module?

**Comment by johntalton** [comment]
# Indeed it is! 🎉

The library uses a normalization of the HID API into a StreamReader / StreamWriter pair ([Stream API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API)), However, the implementation for such a source is not included in this repository as it is a separation-of-concerns, thus allowing for this code to be imported without dependencies and provides both standardization and composability.

## Basics

The following code shows how the MCP2221 can be constructed `from` the [source](https://github.com/johntalton/webapp-device-playground/blob/main/service/node-hid-stream.js)) (it is also - and the primary use case 🥳 - possible to create a WebHID stream [source](https://github.com/johntalton/webapp-device-playground/blob/main/public/util/hid-stream.js) in much the same way) 

Other Node based HID implementation can be created, `node-hid` chosen here.

```javascript
import { MCP2221 } from '@johntalton/mcp2221'
import HID from 'node-hid'

// currently BYOB ... will eventually be published @johntalton/node-hid-stream-source if there is interest?
import { NodeHIDStreamSource } from './hid-stream-source.js'

const source = new NodeHIDStreamSource(device)
const chip = MCP2221.from(source)

// do work ...
const status = await chip.common.status()

```

## I²C
(can skip the remaining sections if not using I²C features)

If the result is to run I²C command, the low level MCP2221 is fully supported (`writeData`, `writeRepeatedSTART`, `readGetData` .. etc)

However, and additional abstraction into a `I2CBus` is possible and convenient.  Addition abstraction of the `I2CAddressedBus` and the example AHT20 temperature sensor.

The `I2CBus` (and its addressed version) provide a more natural I²C interface (aka `readI2CBlock`, `i2cRead`, `writeI2CBlock` ... etc).   

Several "devices" can be then overlayed into of this bus abstraction (as well as other abstraction).  The following example show the use of all of the above abstraction to create AHT20 temperature sensor and call its `getMeasurement` method.


```js
import { I2CBusMCP2221 } from '@johntalton/i2c-bus-mcp2221'
import { I2CAddressedBus } from '@johntalton/and-other-delights'
import { AHT20, DEFAULT_ADDRESS as AHT20_ADDRESS } from '@johntalton/aht20'

// ...
const chip /* from above example */

// create a bus abstraction
const mbus = I2CBusMCP2221.from(chip)

// create a addressed bus
const abus = new I2CAddressedBus(mbus, AHT20_ADDRESS)

// create your device 
const device = AHT20.from(abus)
// ... configure device etc.
const { temperatureC } = await device.getMeasurement()

```

### General sub-note on Javascript async/await interleave call issues.

Additionally, the MCP2221 I²C interactions (and the chip in general) support `async`/`await` syntax.  This does not guard against interleave calls.  Care must be take if the code is to be used in `Worker` threads, or `async` code (example are the use of `Promise.all` to execute multiple bus calls will have un-intended consequences - this is just how javascript works :P).

The `I2CTransactionBus` can help "serialize" the `Promise` calls so that individual bus level calls can be made safe.

### Other uses of the MCP2221 chip

The MCP2221 obviously has a wide range of other features (GPIO, ADC, DAC. etc)

The following is an example of how to clear the Interupt-On-Change flag

```js
const chip /* from above */
await chip.sram.set({ gp: { interrupt: { clear: true } } })
```

### UI

Some screenshots of the MCP2221 in action, currently set as PasswordProtected :)

<img width="1800" alt="Screenshot 2024-07-03 at 1 22 33 PM" src="https://github.com/johntalton/mcp2221/assets/13648537/cd569fcf-b573-40b7-925b-3b7b3221b212">
<img width="1800" alt="Screenshot 2024-07-03 at 1 22 52 PM" src="https://github.com/johntalton/mcp2221/assets/13648537/09920732-df4c-4925-9f9e-6cfee7a23235">
<img width="1800" alt="Screenshot 2024-07-03 at 1 23 10 PM" src="https://github.com/johntalton/mcp2221/assets/13648537/f0097e61-bd5b-4bb1-8312-a5d3013255e4">



Hope that helps,  
let me know if you have other questions or clarification.

**Comment by enthusapp** [comment]
Your playground is brilliant job!

I tested my prototype board for gpio input, and got right "Low" value when I pressed button.

![image](https://github.com/johntalton/mcp2221/assets/30172441/519d8936-07cc-409c-b17a-098870470f6f)

![Screenshot 2024-07-04 at 10 09 38 AM](https://github.com/johntalton/mcp2221/assets/30172441/d024ae02-f937-4a5e-941e-0a2199328898)

Not yet port your module on my node.js application.
After further work, I will tell you the result.

Thanks a lot!

**Comment by enthusapp** [comment]
It works gracefully with your guide.
![image](https://github.com/johntalton/mcp2221/assets/30172441/b505012c-9083-41a3-98ce-1169004b2369)


```js
import { MCP2221 } from '@johntalton/mcp2221';
import HID from 'node-hid';

import { NodeHIDStreamSource } from './node-hid-stream.js'

const mcp2221 = new HID.HID(devices[0].path);
const source = new NodeHIDStreamSource(mcp2221);
const chip = MCP2221.from(source);

let gpio0Status = null;
let gpio1Status = null;

const DEALY = 100;

const gpioCheck = async () => {
  const gpio = await chip.gpio.get();

  const gpio0 = gpio.gpio0.outputValue;
  const gpio1 = gpio.gpio1.outputValue;

  if (gpio0 === gpio0Status && gpio1 === gpio1Status) {
    const d = await new Promise(resolve => setTimeout(() => resolve(), DEALY));
    gpioCheck();
    return;
  }

  gpio0Status = gpio0;
  gpio1Status = gpio1;

  console.log(new Date());
  console.log('gpio0: ' + gpio.gpio0.outputValue);
  console.log('gpio1: ' + gpio.gpio1.outputValue);

  const d = await new Promise(resolve => setTimeout(() => resolve(), DEALY));
  gpioCheck();
};
```

How about adding your guide to `readme.md`?
